services:
  nginx:
    image: nginx:alpine
    ports:
      - "8050:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    image: mohamed20202030/counter_app-web:latest
    # build: .
    expose:
      - "5000"
    depends_on:
      - redis

  redis:
    image: redis:alpine